[database]
url = "sqlite:///chatbot.db"

[smtp]
host = "smtp.gmail.com"
port = 465
username = "ansuashish291@gmail.com"
password = "qjeh fdag ylan lgzw"

[google]
client_id = "410321352574-i67io46kbkl269967uo184mhgsjo85n9.apps.googleusercontent.com"
client_secret = "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"
app_url = "http://localhost:8501/"
